version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/ruby-sinatra-simple
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
  test:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/ruby-sinatra-simple
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install package dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Hello task
          command: bundle exec rake hello

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
